---
- name: install PHP FPM packages
  apt:
    name: [
      "php7.2",
      "php7.2-cli",
      "php7.2-common",
      "php7.2-dev",
      "php7.2-fpm",
      "php7.2-gd",
      "php7.2-intl",
      "php7.2-json",
      "php7.2-mbstring",
      "php7.2-mysql",
      "php7.2-xml"
    ]
    state: present
    update_cache: yes
  notify: start_php_fpm
