---
  - name: start_mariadb
    systemd:
      name: mariadb
      state: started
      enabled: yes

  - name: stop_mariadb
    systemd:
      name: mariadb
      state: stopped

  - name: restart_mariadb
    systemd:
      name: mariadb
      state: restarted
      daemon_reload: yes
